id: P005545
initial_creation_type: ocr
source_metadata:
  id: bdr:W20062
  title: བཤད་རྒྱུད་རྐྱང་སེལ་གྱི་འགྲེལ་བ་མེས་པོའི་དགོངས་རྒྱན།
  author: ''
  volumes:
    f9597315b89a486fb8763932541ed7e0:
      image_group_id: I1KG21604
      title: ''
      volume_number: 1
      total_pages: 236
