id: I94571BBE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:45:42+00:00'
last_modified: '2022-06-08T04:48:57.103251+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20062
  title: བཤད་རྒྱུད་རྐྱང་སེལ་གྱི་འགྲེལ་བ་མེས་པོའི་དགོངས་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B2FC:
      image_group_id: I1KG21604
      title: ''
      total_pages: 236
      order: 1
      base_file: B2FC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
